language: go

go:
  - 1.8.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - bash scripts/multiple_package_coverage_go_workaround.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
